#! /usr/bin/env node
let { existsSync, writeFileSync } = require('fs')
let { execSync } = require('child_process')
let { join } = require('path')
let { DEPLOY, BUILD_ALL } = process.env
let os = process.platform
console.log(`Building Begin... (DEPLOY: ${DEPLOY}, BUILD_ALL: ${BUILD_ALL})`)

/**
 * Node versions: `node14`, `node16`, or latest
 * Platforms:     `alpine`, `linux`, `linuxstatic`, `win`, `macos`
 * Architectures: `x64`, `arm64`
 */
let config = {
  name: 'begin',
  bin: {
    cli: '../src/index.js'
  },
  pkg: {
    // Don't manually include runtimes/deno.js in scripts, as it fails on pkg#997
    scripts: [
      // Begin stuff
      // Some commands have dynamically required subcommands, so just grab everything
      '../src/commands/**/*.js',
      // Arc stuff
      '../node_modules/@architect/inventory/**/*.js',
      '../node_modules/dynalite/**/*.js',
    ],
    assets: [
      '../node_modules/@architect/sandbox/src/invoke-lambda/exec/runtimes/*',
      '../package.json',
      // Enhance stuff
      '../node_modules/@enhance/**/*'
    ],
    targets: [],
    outputPath: 'build',
  }
}

// Main version is derived from the latest git commit
if (DEPLOY === 'main') {
  let cmd = 'git rev-parse HEAD'
  let result = execSync(cmd)
  if (!result) {
    throw ReferenceError('Missing build sha')
  }
  let sha = result.toString().substr(0, 7)
  let appVersion = `main-${sha}`
  let commitFile = join(__dirname, '..', 'commit')
  writeFileSync(commitFile, appVersion)
  config.bin.cli = '../src/_main.js'
  config.pkg.assets.push('../commit')
}

// Handle client IDs in main or prod (and optionally locally)
// However, client IDs should not be required for local testing
let clientIDFile = join(__dirname, '..', 'client-ids.json')
if (DEPLOY) {
  let staging = process.env.BEGIN_CLI_CLIENT_ID_STAGING
  let production = process.env.BEGIN_CLI_CLIENT_ID_PRODUCTION
  if (!staging || !production) {
    throw ReferenceError('Missing staging and/or production client ID')
  }
  let clientIDs = JSON.stringify({ staging, production })
  writeFileSync(clientIDFile, clientIDs)
}
if (existsSync(clientIDFile)) {
  config.pkg.assets.push('../client-ids.json')
}

let nodeVer = `node14`
let arc = 'x64' // TODO: 'arm64'

let platforms = {
  linux: `${nodeVer}-linux-${arc}`,
  darwin: `${nodeVer}-macos-${arc}`,
  win32: `${nodeVer}-win-${arc}`,
}

if (BUILD_ALL === 'true') {
  config.pkg.targets.push(
    platforms.linux,
    platforms.darwin,
    platforms.win32,
  )
}
else {
  let p = str => os.startsWith(str) ? platforms[str] : undefined
  config.pkg.targets = [
    p('linux'),
    p('darwin'),
    p('win32')
  ].filter(Boolean)
}

let path = join(__dirname, 'package.json')
writeFileSync(path, JSON.stringify(config, null, 2))
