name: Binary build

# Push tests pushes
on: [ push ]

defaults:
  run:
    shell: bash

jobs:

  # Test the build
  build:
    # Setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 14.x ]
        os: [ windows-latest, ubuntu-latest, macOS-latest ]

    # Go
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Env
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Git ref:    ${{ github.ref }}"
        echo "GH actor:   ${{ github.actor }}"
        echo "SHA:        ${{ github.sha }}"
        VER=`node --version`; echo "Node ver:   $VER"
        VER=`npm --version`; echo "npm ver:    $VER"

    - name: Install Globals
      run: npm install -g @enhance/arc-plugin-enhance

    - name: Install
      run: npm install

    - name: Build
      run: npm run build
      env:
        BUILD_ALL: false

    - name: Test
      run: npm run test:integration
      env:
        BINARY_ONLY: true
        CI: true

    - name: Notify
      uses: homoluctus/slatify@master
      if: github.ref == 'refs/heads/main' && failure()
      with:
        type: ${{ job.status }}
        job_name: '*Test*'
        url: ${{ secrets.SLACK_WEBHOOK }}
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
