name: Node CI

# Push tests pushes; PR tests merges
on: [ push, pull_request ]

defaults:
  run:
    shell: bash

jobs:

  # Test the build
  test:
    # Setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]
        os: [ windows-latest, ubuntu-latest, macOS-latest ]

    # Go
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Env
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Git ref:    ${{ github.ref }}"
        echo "GH actor:   ${{ github.actor }}"
        echo "SHA:        ${{ github.sha }}"
        VER=`node --version`; echo "Node ver:   $VER"
        VER=`npm --version`; echo "npm ver:    $VER"

    - name: Install Globals
      run: npm install -g @enhance/arc-plugin-enhance

    - name: Install
      run: npm install

    - name: Test
      run: npm test
      env:
        CI: true

    - name: Notify
      uses: homoluctus/slatify@master
      if: github.ref == 'refs/heads/main' && failure()
      with:
        type: ${{ job.status }}
        job_name: '*Test*'
        url: ${{ secrets.SLACK_WEBHOOK }}
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}

  # ----- Only git tag testing + release deployment beyond this point ----- #

  # Deploy the build
  deploy:
    # Setup
    needs: test
    if: startsWith(github.ref, 'refs/tags/v') ||
        github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    # Go
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install
        run: npm i

      - name: Deploy 'latest' (aka production) build
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm run deploy
        env:
          DEPLOY: prod
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BEGIN_CLI_CLIENT_ID_STAGING: ${{ secrets.BEGIN_CLI_CLIENT_ID_STAGING }}
          BEGIN_CLI_CLIENT_ID_PRODUCTION: ${{ secrets.BEGIN_CLI_CLIENT_ID_PRODUCTION }}
          CF_DISTRO: ${{ secrets.CF_DISTRO }}
          LATEST_API: ${{ secrets.LATEST_API }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}

      - name: Deploy 'main' (aka canary) build
        if: github.ref == 'refs/heads/main'
        run: npm run deploy
        env:
          DEPLOY: main
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BEGIN_CLI_CLIENT_ID_STAGING: ${{ secrets.BEGIN_CLI_CLIENT_ID_STAGING }}
          BEGIN_CLI_CLIENT_ID_PRODUCTION: ${{ secrets.BEGIN_CLI_CLIENT_ID_PRODUCTION }}
          CF_DISTRO: ${{ secrets.CF_DISTRO }}
          LATEST_API: ${{ secrets.LATEST_API }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}

      - name: Notify
        uses: homoluctus/slatify@master
        with:
          type: ${{ job.status }}
          job_name: '*Deploy*'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
